In [1]:
# This is a comment (typically single line)
"""
Triple quotes are used for large multi-line comments, and
typically to document functions and modules (Docstrings)
"""

# here is how we print
print "Hello!"
print

Hello!



In [2]:
# here is some math:
a = 1+1		# Sum
b = 2*4		# Multiplication
c = 2**4	# Exponentiation (2^14 = 16)
print "Print variables a, b, c", a, b, c
print

Print variables a, b, c 2 8 16



In [13]:
a,b = 10,3
my_list = [1, 2, 3, 4]

# An if statement: Indentation is critical in python!
if a in my_list and b not in my_list:
	print a, "is in the list"
elif b in my_list and a not in my_list:
	print b, "is in the list"
elif a in my_list and b in my_list:
    print "a ",a," and b ",b," are both in the list"
else:
    print "Neither", a, "or", b, "are in in the list"

3 is in the list


In [14]:
a,b=1,3

list = [1, 2, 3, 4]
					
# An if statement: Indentation is critical in python!
if a in my_list and b not in my_list:
	print a, "is in the list"
elif b in my_list and a not in my_list:
	print b, "is in the list"
elif a in my_list and b in my_list:
	print "a ",a," and b ",b," are both in the list"
else:
	print "Neither", a, "or", b, "are in in the list"

a  1  and b  3  are both in the list


In [2]:
## the range function simply returns a list of numbers in the specified range
range_list=range(1,10)

print
print "range_list is: ", range_list
print

range_list=range(354,363)

print
print "the range_list is: ", range_list
print


range_list is:  [1, 2, 3, 4, 5, 6, 7, 8, 9]


the range_list is:  [354, 355, 356, 357, 358, 359, 360, 361, 362]



In [3]:
## the range function is useful for creating for loops
print "Loop through integers between 1 and 5:"
for i in range(1, 5):
    print "i is: ", i

# is equivalent to

print "Integers between 1 and 5:"
for i in [1,2,3,4,5]:
    print "i is: ", i

Loop through integers between 1 and 5:
i is:  1
i is:  2
i is:  3
i is:  4
Integers between 1 and 5:
i is:  1
i is:  2
i is:  3
i is:  4
i is:  5


In [1]:
print "Loop through a list"

team_list=["Blue Jays", "Yankees", "Red Sox", "Rays", "Orioles"]

for team in team_list:
    print "The team is: ", team

Loop through a list
The team is:  Blue Jays
The team is:  Yankees
The team is:  Red Sox
The team is:  Rays
The team is:  Orioles


In [5]:
# Importing a Python module:
import math
print "[Line 09]", "Python PI=", math.pi # https://docs.python.org/2/library/math.html


# The import statement can occur anywhere in a script
my_teams = ["Blue Jays", "Oilers", "Raptors", "Bills"]
import random
print "A random team:", random.choice(my_teams) # https://docs.python.org/2/library/random.html

[Line 09] Python PI= 3.14159265359
A random team: Bills


In [6]:
# Functions are defined with <def>. Return values are
# specified by a <return> statement. Here is a function
# without arguments:
def today():
    """This function returns a string of today's date"""
    import datetime		# https://docs.python.org/2/library/datetime.html
    td = datetime.date.today()
    return td

In [7]:
print "today() returned", today()
print  "str(today()) returned", str(today())	

today() returned 2015-11-02
str(today()) returned 2015-11-02


In [1]:
import numpy as np

n=10
a_list = range(n)
a_array = np.arange(n)

In [2]:
print a_list
print a_array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
print a_list*2
print a_array*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
a_list.append("dog")
print a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'dog']


In [5]:
a_array.append("dog")

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
mul_list=a_list*3
print mul_list
mul_array=a_array*3
print mul_array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'dog', 'dog', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'dog', 'dog', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'dog', 'dog']
[ 0  3  6  9 12 15 18 21 24 27]


In [7]:
test=np.arange(4,6)
print test

[4 5]


In [10]:
list1=[1,2,3]
list2=[4,5,6]
array1=np.arange(1,4)
array2=np.arange(4,7)

print array1
print array2

list3=list1+list2
array3=array1+array2

print list3
print array3

[1 2 3]
[4 5 6]
[1, 2, 3, 4, 5, 6]
[5 7 9]


In [12]:
array_2d=np.array([[20, 40],[10,20]])
print array_2d
print array_2d.shape

[[20 40]
 [10 20]]
(2, 2)


In [2]:
import numpy as np

array_1d=np.array([233, 12, 100])
print array_1d

# the shape function show the size of the array
print array_1d.shape

[233  12 100]
(3,)


In [14]:
array_2d=np.array([[20, 40],[10,20]])
print array_2d
print array_2d.shape

[[20 40]
 [10 20]]
(2, 2)


In [15]:
test1=array_2d[0,0]
test2=array_2d[0,1]
test3=array_2d[1,0]
test4=array_2d[1,1]
				
print "the numbers are",test1,test2,test3,test4

the numbers are 20 40 10 20


In [19]:
int_array=np.array([0,1,2,3], dtype=np.uint16)
float32_array=np.array([0,1,2,3], dtype=np.float32)

print int_array
print float32_array

[0 1 2 3]
[ 0.  1.  2.  3.]


In [25]:
a=np.arange(15)
print a

b=a[4:11]
print "sliced 4:11",b

c=a[2:12:3]
print "sliced 2:12:3:",c

d=a[-1]
print "indexed -1:",d

e=a[8:2:-1]
print "sliced 2:-10:-2",e

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
sliced 4:11 [ 4  5  6  7  8  9 10]
sliced 2:12:3: [ 2  5  8 11]
indexed -1: 14
sliced 2:-10:-2 [8 7 6 5 4 3]


In [28]:
a=np.arange(15)

print "before reshaping: "
print a
print a.shape

a.shape=(5,3)

print "after reshaping: "
print a
print a.shape

before reshaping: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
after reshaping: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)


In [4]:
test_array=np.arange(20).reshape(4,5)
print test_array

print test_array.ndim
print test_array.shape
print test_array.size

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
(4, 5)
20


In [6]:
print test_array.ndim
print test_array.shape
print test_array.size
print test_array.nbytes
print test_array.itemsize

2
(4, 5)
20
160
8


In [7]:
print test_array.T

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [8]:
import scipy.misc
import matplotlib.pyplot as plt

lena = scipy.misc.lena()
print lena.shape

plt.imshow(lena)
plt.show()

(512, 512)


In [10]:
print type(lena)
print lena.shape
print lena.dtype
print lena.ndim

<type 'numpy.ndarray'>
(512, 512)
int64
2


In [11]:
test_array=np.arange(10)
test_array[ (test_array>3) & (test_array<7)]=15

In [12]:
print test_array

[ 0  1  2  3 15 15 15  7  8  9]


In [11]:
import scipy.io.wavfile
import matplotlib.pyplot as plt
import urllib2
import numpy as np

response = urllib2.urlopen('http://www.thesoundarchive.com/austinpowers/smashingbaby.wav')
print response.info()
WAV_FILE = 'austin.wav'
filehandle = open(WAV_FILE, 'w')
filehandle.write(response.read())
filehandle.close()

Content-Type: audio/wav
Last-Modified: Tue, 12 Aug 2014 15:53:38 GMT
Accept-Ranges: bytes
ETag: "ac20ba9445b6cf1:0"
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Sat, 14 Nov 2015 16:43:42 GMT
Connection: close
Content-Length: 43642



In [12]:
print WAV_FILE
sample_rate, data = scipy.io.wavfile.read('vader.wav')
print "Data type", data.dtype, "Shape", data.shape

austin.wav
Data type uint8 Shape (43584,)


In [ ]:
plt.title("Sound File")
plt.plot(data)
plt.show()
