## Numpy

Import numpy and create a simple array

In [1]:
import numpy as np

test=np.arange(10)
print test
print type(test)

[0 1 2 3 4 5 6 7 8 9]
<type 'numpy.ndarray'>


Create a list and an array

In [2]:
n=10
a_list = range(n)
a_array = np.arange(n)

print type(a_list)
print a_list
print
print type(a_array)
print a_array

<type 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

<type 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


Multiplying the list vs multiplying the array

In [3]:
mul_list=a_list*3
print mul_list
mul_array=a_array*3			
print mul_array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  3  6  9 12 15 18 21 24 27]


Adding lists vs adding vectors

In [16]:
list1=[1,2,3]
list2=[4,5,6]
array1=np.arange(1,4)
array2=np.arange(4,7)

list3=list1+list2
array3=array1+array2

print list3
print array3

[1, 2, 3, 4, 5, 6]
[5 7 9]


Raise to a power

In [18]:
#pow_list=a_list**3
#print pow_list
pow_array=a_array**3	
print pow_array

[  0   1   8  27  64 125 216 343 512 729]


Initialize an array and show the shape

In [19]:
array_1d=np.array([1,2,3,4])

print type(array_1d)
print array_1d
print array_1d.shape

<type 'numpy.ndarray'>
[1 2 3 4]
(4L,)


Access elements

In [21]:
test1=array_1d[0]
test2=array_1d[1]					
test3=array_1d[2]					
				
print "the numbers are",test1,test2,test3

the numbers are 1 2 3


Create a 2d array

In [3]:
array_2d=np.array([[20, 40],[10,20]])
print array_2d
print array_2d.shape

[[20 40]
 [10 20]]
(2L, 2L)


Access elements (2d)

In [7]:
test1=array_2d[0,0]
test2=array_2d[0,1]
test3=array_2d[1,0]
test4=array_2d[1,1]
				
print "the numbers are",test1,test2,test3,test4

the numbers are 20 40 10 20


In [8]:
print type(test1)

<type 'numpy.int32'>


Numpy Arrays can have different types

In [9]:
int_array=np.array([0,1,2,3], dtype=np.uint16)
float32_array=np.array([0,1,2,3], dtype=np.float32)

print int_array
print float32_array

[0 1 2 3]
[ 0.  1.  2.  3.]


## Slicing arrays

In [10]:
a=np.arange(15)
print a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
sliced 4:11 [ 4  5  6  7  8  9 10]
sliced 2:12:3: [ 2  5  8 11]
indexed -1: 14
sliced 2:-10:-2 [8 7 6 5 4 3]


Slice elements 4 through 11

In [23]:
b=a[4:11]
print "sliced 4:11",b

sliced 4:11 [ 4  5  6  7  8  9 10]


Slice elements 2 through 12, incrementing by 3

In [24]:
c=a[2:12:3]
print "sliced 2:12:3:",c

sliced 2:12:3: [ 2  5  8 11]


Access the last element (a tricky way)

In [26]:
d=a[-1]
print "indexed -1:",d


indexed -1: 14


Access elements backwards

In [27]:
e=a[8:2:-1]
print "sliced 2:-10:-2",e

sliced 2:-10:-2 [8 7 6 5 4 3]


Reshape an array

In [29]:
a=np.arange(15)

print "before reshaping: "
print a
print
print a.shape

a.shape=(5,3)

print "after reshaping: "
print a
print
print a.shape

before reshaping: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

(15L,)
after reshaping: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

(5L, 3L)


Array atributes

In [32]:
test_array=np.arange(20).reshape(4,5)

print "test array:"
print test_array
print
print "dims: ",test_array.ndim
print
print "shape: ",test_array.shape
print
print "size: ",test_array.size
print
print "number bytes: ",test_array.nbytes
print
print "item size: ",test_array.itemsize

test array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

dims:  2

shape:  (4L, 5L)

size:  20

number bytes:  80

item size:  4


Conditional indexing

In [ ]:
test_array=np.arange(10)
print test_array

test_array[ (test_array>3) & (test_array<7)]=15
print test_array